import React, { useState } from 'react';
import { Calendar, Droplets, MapPin, Sprout, Thermometer } from 'lucide-react';
import api from '../services/api';
import PageTransition from '../components/PageTransition';

const YieldPrediction = () => {
  const [formData, setFormData] = useState({
    cropType: '',
    area: '',
    season: '',
    state: '',
    rainfall: '',
    temperature: ''
  });
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const seasons = ['Kharif', 'Rabi', 'Zaid', 'Whole Year'];
  const states = ['Punjab', 'Haryana', 'Uttar Pradesh', 'Maharashtra', 'Madhya Pradesh', 'Andhra Pradesh', 'Tamil Nadu'];
  const handleChange = (e) => {
    setFormData({ ...formData, [e.target.name]: e.target.value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setLoading(true);
    setError('');
    setResult(null);

    try {
      const payload = {
        cropType: formData.cropType.trim(),
        area: Number(formData.area),
        season: formData.season,
        state: formData.state,
        rainfall: Number(formData.rainfall),
        temperature: Number(formData.temperature)
      };
      const res = await api.post('/yield/predict', payload);
      if (res.data.success) {
        setResult(res.data.data);
      }
    } catch (err) {
      setError(err.response?.data?.message || 'Failed to forecast yield. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <PageTransition>
      <div className="min-h-screen bg-gray-50 dark:bg-gray-900 py-12 transition-colors">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-10">
            <h1 className="text-3xl md:text-4xl font-black text-gray-900 dark:text-white">Yield Prediction Model</h1>
            <p className="mt-3 text-gray-600 dark:text-gray-400 max-w-3xl mx-auto">
              Provide all production parameters. Result is generated by Farmix yield model and includes confidence, model accuracy, and data source.
            </p>
          </div>

          <div className="card p-8">
            {error ? (
              <div className="mb-5 rounded-xl bg-red-50 dark:bg-red-900/40 p-3 text-sm text-red-700 dark:text-red-300">
                {error}
              </div>
            ) : null}

            <form onSubmit={handleSubmit} className="space-y-5">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                <div>
                  <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">
                    <span className="inline-flex items-center gap-2">
                      <Sprout className="w-4 h-4 text-emerald-600" />
                      Crop Type
                    </span>
                  </label>
                  <input
                    type="text"
                    name="cropType"
                    required
                    placeholder="wheat"
                    value={formData.cropType}
                    onChange={handleChange}
                    className="input-field"
                  />
                </div>
                <div>
                  <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">Area (hectares)</label>
                  <input
                    type="number"
                    name="area"
                    required
                    min="0.1"
                    step="0.1"
                    value={formData.area}
                    onChange={handleChange}
                    className="input-field"
                  />
                </div>
                <div>
                  <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">
                    <span className="inline-flex items-center gap-2">
                      <Calendar className="w-4 h-4 text-orange-500" />
                      Season
                    </span>
                  </label>
                  <select
                    name="season"
                    required
                    value={formData.season}
                    onChange={handleChange}
                    className="input-field"
                  >
                    <option value="">Select season</option>
                    {seasons.map((season) => (
                      <option key={season} value={season}>{season}</option>
                    ))}
                  </select>
                </div>

                <div>
                  <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">
                    <span className="inline-flex items-center gap-2">
                      <MapPin className="w-4 h-4 text-red-500" />
                      State
                    </span>
                  </label>
                  <select
                    name="state"
                    required
                    value={formData.state}
                    onChange={handleChange}
                    className="input-field"
                  >
                    <option value="">Select state</option>
                    {states.map((state) => (
                      <option key={state} value={state}>{state}</option>
                    ))}
                  </select>
                </div>
                <div>
                  <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">
                    <span className="inline-flex items-center gap-2">
                      <Droplets className="w-4 h-4 text-blue-500" />
                      Rainfall (mm)
                    </span>
                  </label>
                  <input
                    type="number"
                    name="rainfall"
                    required
                    min="0"
                    value={formData.rainfall}
                    onChange={handleChange}
                    className="input-field"
                  />
                </div>
                <div>
                  <label className="block text-sm font-semibold text-gray-700 dark:text-gray-300 mb-2">
                    <span className="inline-flex items-center gap-2">
                      <Thermometer className="w-4 h-4 text-orange-500" />
                      Temperature (C)
                    </span>
                  </label>
                  <input
                    type="number"
                    name="temperature"
                    required
                    value={formData.temperature}
                    onChange={handleChange}
                    className="input-field"
                  />
                </div>

              </div>

              <button
                type="submit"
                disabled={loading}
                className="w-full rounded-xl bg-emerald-600 px-4 py-3 text-sm font-bold text-white hover:bg-emerald-700 disabled:opacity-60"
              >
                {loading ? 'Running model...' : 'Generate Yield Prediction'}
              </button>
            </form>
          </div>

          {result ? (
            <div className="mt-6 card p-8">
              <h3 className="text-lg font-black text-gray-900 dark:text-white">Model Result</h3>
              <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
                <div className="rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800 p-4">
                  <p className="text-xs font-black uppercase tracking-wider text-gray-400">Yield Per Hectare</p>
                  <p className="mt-1 text-2xl font-black text-emerald-700 dark:text-emerald-400">
                    {result.estimatedYield}
                  </p>
                </div>
                <div className="rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800 p-4">
                  <p className="text-xs font-black uppercase tracking-wider text-gray-400">Total Yield</p>
                  <p className="mt-1 text-2xl font-black text-gray-900 dark:text-white">
                    {result.totalYield || 'N/A'}
                  </p>
                </div>
              </div>

              <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-3">
                <div className="rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800 p-3">
                  <p className="text-xs font-black uppercase tracking-wider text-gray-400">Confidence</p>
                  <p className="mt-1 text-base font-bold text-gray-900 dark:text-white">
                    {Math.round(Number(result.confidence || 0) * 100)}%
                  </p>
                </div>
                <div className="rounded-xl border border-gray-200 dark:border-gray-700 bg-gray-50 dark:bg-gray-800 p-3">
                  <p className="text-xs font-black uppercase tracking-wider text-gray-400">Model Source</p>
                  <p className="mt-1 text-sm font-bold text-gray-900 dark:text-white">
                    {result.modelSource || 'Farmix Model'}
                  </p>
                </div>
              </div>

              <p className="mt-4 text-sm text-gray-600 dark:text-gray-400">
                Data Source: {result.dataSource || 'Farm data model'}
              </p>
            </div>
          ) : null}
        </div>
      </div>
    </PageTransition>
  );
};

export default YieldPrediction;
